function [XDEN,cfsDEN,dimCFS] = func_denoise_dw2d(X)
% FUNC_DENOISE_DW2D Saved Denoising Process.
%   X: matrix of data
%   -----------------
%   XDEN: matrix of denoised data
%   cfsDEN: decomposition vector (see WAVEDEC2)
%   dimCFS: corresponding bookkeeping matrix

%  Auto-generated by Wavelet Toolbox on 10-Mar-2022 17:26:37

% Analysis parameters.
%---------------------
wname = 'haar';
level = 2;

% Denoising parameters.
%-----------------------
% meth = 'sqtwolog';
% scal_OR_alfa = mln;
sorh = 's';    % Specified soft or hard thresholding
thrSettings =  [...
    10.792400652741627     13.573813634836984 ; ...
    10.792400652741627     13.573813634836984 ; ...
    10.792400652741627     13.573813634836984   ...
    ];
roundFLAG = true;

% Denoise using WDENCMP.
%----------------------
[coefs,sizes] = wavedec2(X,level,wname);
[XDEN,cfsDEN,dimCFS] = wdencmp('lvd',coefs,sizes, ...
    wname,level,thrSettings,sorh);
if roundFLAG , XDEN = round(XDEN); end
if isequal(class(X),'uint8') , XDEN = uint8(XDEN); end
