function [B,varargout] = loadBin(fname)
%
%   loadBin(fname) - loads bin file generated by the LabView program 
%    for laser scanner scanner
%
%   usage: 
%       B = loadBin(fname) 
%             - reads Bscan from the measurement file fname
%       [B,n_Ascans,n_pts] = loadBin(fname)  
%             - reads Bscan, number of A scans and number of points in a
%               single Ascan 
%       fname - is a string with filename. 
%      
%
[FID, MESSAGE] = fopen(fname,'r','ieee-be');

N = fread(FID,2,'int32' );
n_Ascans = N(1);    n_pts 	 = N(2);  

a = fread(FID,n_pts*n_Ascans,'double' );
fclose(FID);
B = reshape(a,n_pts,n_Ascans);

nout = max(nargout,1)-1;
if nout==2
    varargout(1) = {n_Ascans};
    varargout(2) = {n_pts};
elseif nout==0
else
    error('The function can return 1 or 3 values')
end
% end of function