clc;
clear;
close all;

Sample = struct('c22_fiber', 12.13e9, ... 
    'c22_r_fiber', 13.21e9, ...
    'c22_i_fiber', 0.49e9, ...
    'E_resin', 3.7e9, ...
    'poisson_resin', 0.4, ...
    'G_resin', 1.32e9, ...
    'rho_fiber', 1528, ...  % density
    'rho_resin', 1270, ... % to be determined further
    'db_fiber', 0.02e-3, ... % complex velcity includes the info. of damping 
    'db_resin', 0.15e-3, ...
    'h_fiber', 217e-6, ... % thinknesses
    'h_resin', 3e-6, ...
    'alpha_fiber_shear', 0, ... % whatever, not used ...
    'alpha_resin_shear', 0, ...
    'v_fiber_shear', 0, ...
    'v_resin_shear', 0 );

% formula for longitudinal velocities
c22_fiber = Sample.c22_r_fiber + 1i * Sample.c22_i_fiber;
v_fiber = sqrt(c22_fiber / Sample.rho_fiber);

% attenuation calculation
db_fiber = Sample.db_fiber/10*log(10); % transfer db to dimensionless ratio

alpha = real(1i*2*pi/v_fiber);

db_fiber_comlex = alpha *10/log(10);